### PR TITLE
Get the real cwd from darwin

### LINKED ISSUE #491: NFS mount fails on mac os due to terminal being case-insensitive
Given that a folder name is `Projects` and you cd into the folder in a mac os terminal using `cd projects` (which is valid and results in `Calvins-MacBook-Pro:projects calvin$`), starting a nanobox with `nanobox run` fails with:

```
Error   : mount: output: mount: 192.168.99.1:/Users/calvin/projects/rails-app failed, reason given by server: Permission denied
mount: mounting 192.168.99.1:/Users/calvin/projects/rails-app on /share/83d0a9501468d27d5455238eb4feb03c/code failed: Bad file descriptor
exit status 110
 err:exit status 1
Context : failed to init docker client -> failed to setup env mounts -> failed to mount the code share on the provider
```

This is due to nanobox-desktop taking the path as it is being represented in the mac os terminal (case-insensitive) and using it with the vm (case-sensitive).

If you move into the path with `cd Projects` (mind the capital p) and then initialise the nanobox, everything works as expected.

### PR DESCRIPTION
**Pull request by glinton**
Resolves #491

### CODE REVIEW

File: util/config/dirs.go [hunk 1]
```diff
@@ -30,11 +31,20 @@ func GlobalDir() string {
...
 func LocalDir() string {
+	var cwd string
+	var err error
 
-	//
-	cwd, err := os.Getwd()
-	if err != nil {
-		return ""
+	// use syscall if possible (os uses $PWD, causing irregularities on darwin)
+	if syscall.ImplementsGetwd {
```
Comment (glinton) [inline util/config/dirs.go]: This should make using `syscall` safe until go's issue is resolved
